#ifndef GAME_CTRL_DEFINES_HPP_INCLUDED
#define GAME_CTRL_DEFINES_HPP_INCLUDED

constexpr auto COLLIDER_TYPE_FRIEND_TANK = "FT";
constexpr auto COLLIDER_TYPE_ENEMY_TANK = "ET";
constexpr auto COLLIDER_TYPE_JEBEL_LANDSPACE = "JL";
constexpr auto COLLIDER_TYPE_GRASS_LANDSPACE = "GL";

#endif